-- #################################
-- ######### 관리자 (ADMIN) #########
-- #################################
-- // TODO :: 이름, 이메일, 휴대폰 번호 컬럼 추가
DROP TABLE IF EXISTS ADMIN CASCADE;
CREATE TABLE ADMIN (
    `ADMIN_NO`		INT NOT NULL AUTO_INCREMENT COMMENT '식별자',
    `ADMIN_ID`		VARCHAR(16) NOT NULL COMMENT '관리자 아이디',
    `ADMIN_PWD`		VARCHAR(128) NOT NULL COMMENT '관리자 패스워드',
    `ADMIN_AUTH`	VARCHAR(16) NOT NULL COMMENT '관리자 권한',
    `ADMIN_STATUS`	CHAR(2) NOT NULL COMMENT '관리자 상태',
    `FAIL_CNT`		INT NOT NULL DEFAULT 0 COMMENT '비밀번호 실패 횟수',
    `LOGIN_DT`		DATETIME COMMENT '로그인 일시',
    `PWD_DT`		DATETIME COMMENT '패스워드 변경일시',
    `REG_DT`		DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    `MOD_DT`		DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY(`ADMIN_NO`)
);
CREATE UNIQUE INDEX `ADMIN_ADMIN_ID_IDX1` ON ADMIN (`ADMIN_ID`);

-- #################################
-- ###### 고객센터 (CUSTOMER) #######
-- #################################
-- 공지사항
DROP TABLE IF EXISTS CUSTOMER_NOTICE CASCADE;
CREATE TABLE CUSTOMER_NOTICE (
    `NOTICE_NO`     INT NOT NULL AUTO_INCREMENT COMMENT '식별자',
    `TITLE`         VARCHAR(100) NOT NULL COMMENT '제목',
    `CONTENTS`      TEXT NOT NULL COMMENT '내용',
    `NOTICE_TYPE`   CHAR(2) NOT NULL COMMENT '공지 유형',
    `HITS`          INT NOT NULL DEFAULT 0 COMMENT '조회수',
    `DISPLAY_YN`    CHAR(1) NOT NULL DEFAULT 'N' COMMENT '노출 여부(Y/N)',
    `REG_DT`        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    `MOD_DT`        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY(`NOTICE_NO`)
);
-- 공지사항 첨부파일 정보
DROP TABLE IF EXISTS CUSTOMER_NOTICE_FILE CASCADE;
CREATE TABLE CUSTOMER_NOTICE_FILE (
    `NOTICE_FILE_NO`    INT NOT NULL AUTO_INCREMENT COMMENT '식별자',
    `NOTICE_NO`     	INT NOT NULL COMMENT '공지글 번호',
    `FILE_NAME`     	VARCHAR(36) NOT NULL COMMENT '파일명',
    `ORG_FILE_NAME` 	VARCHAR(260) NOT NULL COMMENT '원본 파일명',
    `REG_DT`        	DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    PRIMARY KEY(`NOTICE_FILE_NO`)
);
-- 자주하는질문
DROP TABLE IF EXISTS CUSTOMER_FAQ CASCADE;
CREATE TABLE CUSTOMER_FAQ (
    `FAQ_NO`            INT NOT NULL AUTO_INCREMENT COMMENT '식별자',
    `QUESTION`          VARCHAR(100) NOT NULL COMMENT '질문',
    `ANSWER`            TEXT NOT NULL COMMENT '답변',
    `FAQ_TYPE`          CHAR(2) NOT NULL COMMENT '질문 유형',
    `HITS`              INT NOT NULL DEFAULT 0 COMMENT '조회수',
    `DISPLAY_YN`        CHAR(1) NOT NULL DEFAULT 'N' COMMENT '노출 여부(Y/N)',
    `DISPLAY_TOP_YN`    CHAR(1) NOT NULL DEFAULT 'N' COMMENT '상단 노출 여부(Y/N)',
    `REG_DT`            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    `MOD_DT`            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY(`FAQ_NO`)
);